# tasks file for tinyproxy
---
- name: include variables
  include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-include-variables

- name: install dependencies
  apt:
    name: "{{ tinyproxy_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-dependencies

- name: install additional
  apt:
    name: "{{ tinyproxy_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-install

- name: update configuration file
  template:
    src: etc/tinyproxy.conf.j2
    dest: "{{ tinyproxy_configuration_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart tinyproxy
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-configuration

- name: start and enable service
  service:
    name: tinyproxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  when: ansible_service_mgr == 'systemd'
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-start-enable-service
    - tinyproxy-start-enable-service-systemd

# TODO: Remove when support for Ubuntu 14.04 is dropped
- name: start and enable service
  service:
    name: tinyproxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
    pattern: /usr/sbin/tinyproxy
  when: ansible_service_mgr != 'systemd'
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-start-enable-service
    - tinyproxy-start-enable-service-initd
