# tasks file for tinyproxy
---

- debug:
    msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"
  tags:
    - debug
    - never
- debug:
    msg: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
  tags:
    - debug
    - never
- debug:
    msg: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"
  tags:
    - debug
    - never

- name: include OS specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"


- name: update configuration file
  template:
    src: etc/tinyproxy.conf.j2
    dest: "{{ tinyproxy_configuration_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart tinyproxy
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-configuration

- name: start and enable service
  service:
    name: tinyproxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  when: ansible_service_mgr == 'systemd'
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-start-enable-service
    - tinyproxy-start-enable-service-systemd

# TODO: Remove when support for Ubuntu 14.04 is dropped
- name: start and enable service
  service:
    name: tinyproxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
    pattern: /usr/sbin/tinyproxy
  when: ansible_service_mgr != 'systemd'
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-start-enable-service
    - tinyproxy-start-enable-service-initd
