# tasks file for tinyproxy
---
- name: include variables
  include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - tinyproxy
    - tinyproxy-include-variables

- name: repository install tinyproxy
  block:
    - name: install dependencies
      apt:
        name: "{{ tinyproxy_dependencies }}"
        state: "{{ apt_install_state | default('latest') }}"
        update_cache: true
        cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
      tags:
        - tinyproxy
        - tinyproxy-dependencies

    - name: install additional
      apt:
        name: "{{ tinyproxy_install }}"
        state: "{{ apt_install_state | default('latest') }}"
  when: not local_install
  tags:
    - tinyproxy
    - tinyproxy-install

- name: local install tinyproxy
  block:
    - name: remove old version
      apt:
        name: tinyproxy
        state: absent

    - name: install packages
      apt:
        deb: "{{ item.value }}"
      loop: "{{ local_list_packages | dict2items | sort }}"

  when: local_install
  tags:
    - tinyproxy
    - tinyproxy-install

- name: update configuration file
  template:
    src: etc/tinyproxy.conf.j2
    dest: "{{ tinyproxy_configuration_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart tinyproxy
  tags:
    - tinyproxy
    - tinyproxy-configuration

- name: start and enable service
  service:
    name: tinyproxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - tinyproxy
    - tinyproxy-start-enable-service
    - tinyproxy-start-enable-service-systemd
    