# tasks file for tinyproxy
---

# - name: include variables
#   include_vars: "{{ item }}"
#   with_first_found:
#     - "_{{ ansible_os_family }}.yml"
#     - "_{{ ansible_distribution_release }}.yml"
#     - "_{{ ansible_distribution | lower }}.yml"
#     - _default.yml
#   tags:
#     - configuration
#     - tinyproxy
#     - tinyproxy-include-variables

- name: Set fact for Debian
  set_fact:
    tinyproxy_configuration_file: /etc/tinyproxy.conf
    proxy_user: nobody
    proxy_group: nogroup
  when: 
    - ansible_distribution == "Ubuntu" 
    - ansible_distribution_major_version == "16"

- name: RedHat | Install the latest version of Tinyproxy
  yum:
    name: "{{ tinyproxy_dependencies }}"
    state: "{{ package_install_state | default('latest') }}"
    enablerepo: epel
  when: 
    - ansible_os_family == 'RedHat'

- name: Debian | Install the latest version of Tinyproxy
  package:
    name: "{{ tinyproxy_dependencies }}"
    state: "{{ package_install_state | default('latest') }}"
  when: 
    - ansible_os_family == 'Debian'
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-dependencies

- name: install additional
  apt:
    name: "{{ tinyproxy_install }}"
    state: "{{ package_install_state | default('latest') }}"
  when: 
    - ansible_os_family == 'Debian'
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-install

- name: update configuration file
  template:
    src: etc/tinyproxy.conf.j2
    dest: "{{ tinyproxy_configuration_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart tinyproxy
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-configuration

- name: start and enable service
  service:
    name: tinyproxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  when: ansible_service_mgr == 'systemd'
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-start-enable-service
    - tinyproxy-start-enable-service-systemd

# TODO: Remove when support for Ubuntu 14.04 is dropped
- name: start and enable service
  service:
    name: tinyproxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
    pattern: /usr/sbin/tinyproxy
  when: ansible_service_mgr != 'systemd'
  tags:
    - configuration
    - tinyproxy
    - tinyproxy-start-enable-service
    - tinyproxy-start-enable-service-initd
