---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: include vars
      ansible.builtin.include_vars: "{{ playbook_dir }}/../../tests/vars/main.yml"
    - name: include tasks
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../../tests/tasks/post.yml"
